name: Build and Release EXE

on:
  push:
    branches:
      - main  # Trigger this on pushes to the 'main' branch
  release:
    types:
      - created  # Trigger this on new release creation

jobs:
  build:
    runs-on: windows-latest  # Use Windows for EXE generation

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        pip install --upgrade pip  # Ensure pip is up-to-date
        # Install precompiled Pillow binaries for Python 3.12 to avoid compilation issues
        pip install Pillow --find-links https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow
        pip install -r requirements.txt  # Install project dependencies

    - name: Install PyInstaller
      run: |
        pip install pyinstaller  # Install PyInstaller to build EXE

    - name: Build EXE with Icon
      run: |
        pyinstaller --onefile --icon=doi2bibtex.ico doi2bibtex.py  # Create EXE with custom icon

    - name: Create Tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a v8 -m "Release v8"  # Create the tag
        git push origin v8  # Push the tag to GitHub

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication

    - name: Upload EXE to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/doi2bibtex.exe  # Path to the generated EXE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
