name: Build and Release EXE

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  release:
    types:
      - created  # Trigger on new release creation

permissions:
  contents: write  # Ensure the workflow has write permissions

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install Pillow --find-links https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build EXE with Icon
      run: |
        pyinstaller --onefile --icon=doi2bibtex.ico doi2bibtex.py

    - name: Determine Version
      id: get_version  # Assign an ID for this step to reference the output
      run: |
        VERSION=$(python setup.py --version)  # Replace with your preferred method of fetching the version
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create Tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a $VERSION -m "Release $VERSION"  # Use the dynamically determined version
        git push origin $VERSION
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Fetch Tags
      run: |
        git fetch --tags

    - name: Upload EXE to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/doi2bibtex.exe
        tag_name: ${{ env.VERSION }}  # Use the dynamically determined version for the release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
