name: Build and Release EXE

on:
  push:
    branches:
      - main
  release:
    types:
      - created

permissions:
  contents: write  # Ensure the workflow can write to the repository

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install Pillow --find-links https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build EXE with Icon
      run: |
        pyinstaller --onefile --icon=doi2bibtex.ico doi2bibtex.py

    - name: Create Tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a v8 -m "Release v8"
        git push origin v8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload EXE to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/doi2bibtex.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
